spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://123.56.138.30:3306/brt
#    type: com.mysql.cj.jdbc.MysqlDataSource
#    username: root
#    password: root123

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.204.136.225:3306/brt
    type: com.mysql.cj.jdbc.MysqlDataSource
    username: brt
    password: 123456@brt.

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: 1
      logic-not-delete-value: 0

llm:
  qianfan:
    api-key: 8oDtfGdZgs5Tgtu7AkP9n3HI
    api-secret: bdfVt1eXzoC02wyBZFKKlPePiz7CnfeT
    model-name: Yi-34B-Chat
  openai:
    secret-key: <KEY>
    model-name: <MODEL_NAME>


files:
  upload:
    base-path: D:/xz/WS/temp/upload/
  download:
    base-url: http://60.204.136.225:6000/brt/file/download/